---
- name: Installing Package
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Installing the latest version of Apache
      yum:
        name: httpd
        state: latest

    - name: Starting the service of Apache
      service:
        name: httpd
        state: started

    - name: Enabled the Service
      service:
        name: httpd
        enabled: yes
