---
# tasks file for tomcat_setup_roll
- name: creating a user called {{ user_name }}
  user: 
    name: "{{ user_name }}"
    state: present

- name: Updating System
  yum: 
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: installing java and wget on target system
  yum:
    name: ['java-1.8*', 'wget']
    state: latest
  when: ansible_os_family == "RedHat"

- name: downloading tomcat package
  get_url:
    url: "{{ tomcat_url }}"
    dest: /opt 
    mode: 0755

- name: extracting tomcat package
  unarchive:
    src: /opt/{{ tomcat_package }}.tar.gz
    dest: /opt
    remote_src: yes

- name: change the ownership on the tomcat folder
  file: 
    path: /opt/{{ tomcat_package }}
    mode: 0755
    recurse: yes

- name: creating link file for tomcat service
  file:
    src: /opt/{{ tomcat_package }}/bin/{{ item.tomcat_script }}
    dest: /usr/local/bin/{{ item.tomcat_cmd }}
    state: link
  loop:
    - { tomcat_script: 'startup.sh', tomcat_cmd: 'tomcatup'  }
    - { tomcat_script: 'shutdown.sh', tomcat_cmd: 'tomcatdown'  }
  notify: start the service

- name: change the port number
  copy:
    src: server.xml
    dest: /opt/{{ tomcat_package }}/conf/server.xml
  notify: restart the service
